### ISSUE TITLE
Move to an org

### ISSUE THREAD

**Issue by jbenet** [dnslink-std/dnslink-website#1]
This should be in any of:
- multiformats
- ipfs-shipyard
- ipfs
- protocol

Lmk which and i'll move it

**Comment by martinheidegger** [comment]
How about a new organization for dnslink?

**Comment by martinheidegger** [comment]
After conversation with @lidel I created https://github.com/dnslink-std and invited you as an owner.

**Comment by lidel** [comment]
note to self: I think we may solve #11 by moving  + setting up http://fleek.co/

**Comment by lidel** [comment]
Done! https://github.com/dnslink-std/dnslink-website
