### ISSUE TITLE
Fix DNSLink publishing (dnslink.io and dnslink.dev)

### ISSUE THREAD

**Issue by lidel** [dnslink-std/dnslink-website#11]
It is broken right now (invalid DNSSIMPLE token?):
https://github.com/ipfs/dnslink-website/runs/2632605780#step:12:7

(same issue for `dnslink.io` and `dnslink.dev`)

@mburns do you have a sense of what's wrong? Is the fix re-adding token or do we need to have separate one for each domain?

**Comment by lidel** [comment]
@mburns ping – I've re-run job but the same token error is printed: https://github.com/ipfs/dnslink-website/runs/2779095871?check_suite_focus=true#step:11:8:

```
 npx dnslink-dnsimple --domain dnslink.io --link /ipfs/bafybeicurvyneoolixzsbsnscukduxrsocgp4a4z7uyfiflafz7au6menq
  shell: /usr/bin/bash -e {0}
  env:
    DNSIMPLE_TOKEN: ***
Failed to find zone record for dnslink.io with the token provided. Did you use the wrong token?

```

**Comment by lidel** [comment]
I moved the website repo to https://github.com/dnslink-std org – we no longer use collab cluster, but I've enabled Fleek publishing.

Preview of the main branch is at: https://dnslink-website.on.fleek.co


Remaining work – I need one-time infra help with this:

- [ ] update DNS for `dnslink.dev` (main name) to point at Fleek:
  > ![2021-06-22--11-54-23](https://user-images.githubusercontent.com/157609/122904570-c15eec00-d350-11eb-9ee1-2639b96aac26.png)
  - [ ] `dnslink.dev`
    > ![2021-06-22--11-54-43](https://user-images.githubusercontent.com/157609/122904614-ccb21780-d350-11eb-98cf-432d9f4c1fec.png)
  - [ ] `www.dnslink.dev`
    > ![2021-06-22--11-55-02](https://user-images.githubusercontent.com/157609/122904701-ddfb2400-d350-11eb-9c1d-39e41d4e5e1f.png)



- [ ] set DNSLink at `dnslink.io` to `dnslink=/ipfs/bafkreidj5lipga46mwq4wdkrrmarjmppobvtsqssge6o5nhkyvsp6pom3u` – a static redirect page pointing at `dnslink.dev` as the canonical variant

**Comment by mburns** [comment]
I've split off the 3 `dnslink.{dev,io,org}` domains into their own DNSimple account and added the relevant Github Secrets for as env vars (`$DNSIMPLE_TOKEN`, `$DNSIMPLE_ACCOUNT`).

> update DNS for dnslink.dev (main name) to point at Fleek:

I'm ready to cut this over, but doing so will expose a TLS error until the Fleek cert is updated. Let me know when you're at the keyboard and we can make the change live.

**Comment by martinheidegger** [comment]
@mburns awesome! Thank you. In https://github.com/dnslink-std/test/pull/3 the dnsimple token/account would also be needed, would it be okay to set the tokens for the organization?

**Comment by mburns** [comment]
I've added `DNSIMPLE_ACCOUNT`/`DNSIMPLE_TOKEN` as secrets to dnslink-std/test

**Comment by lidel** [comment]
Done! https://dnslink.dev loads from Fleek and https://dnslink.io redirects to it.
Thanks for help @mburns :raised_hands: :heart:
